apiVersion: v1
kind: Service
metadata:
  name: web-service-d
  namespace: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007

